#!/data/data/com.termux/files/usr/bin/bash

cleanup() {
    pg_ctl -D ./database stop > /dev/null 2>&1
    echo "Server telah berhenti"
    exit 0
}

ENV_FILE="./cbt/.env"
KEY="SERVER_SECRET_LICENSE_KEY"
KEY_FILE="./cbt/database/.key"

# Check if DNS is listening on [::1]:53
if ! nc -z -u -w1 ::1 53; then
    echo "Error: DNS tidak aktif di [::1]:53, tolong aktifkan hotspot."
    exit 1
fi

clear

if [[ ! -f "$ENV_FILE" ]]; then
    echo "Error: tidak ditemukan .env di $ENV_FILE"
    echo "Pastikan Ekstraordinary CBT telah dipasang"
    echo "menggunakan naskah atau script utama"
    exit 1
fi

# Ambil lisensi dari file .key jika ada dan tidak kosong
if [[ -s "$KEY_FILE" ]]; then
    VALUE=$(<"$KEY_FILE")
else
    echo "Kunci lisensi tidak ditemukan atau kosong."
    echo "Dapatkan Lisensi di https://ecosystem.ekstraordinary.com, lalu"
    read -p "Masukkan Kunci Lisensi: " VALUE
    echo "$VALUE" > "$KEY_FILE"
fi

# Perbarui isi ENV_FILE
if grep -q "^$KEY=" "$ENV_FILE"; then
    sed -i "s/^$KEY=.*/$KEY=$VALUE/" "$ENV_FILE"
else
    echo "$KEY=$VALUE" >> "$ENV_FILE"
fi

# Set STORAGE_PATH
sed -i 's|^STORAGE_PATH=.*|STORAGE_PATH='"$PWD"'/cbt/storage|' "$ENV_FILE"

echo "Kunci Lisensi telah dipasang."
echo ""
echo "================================="
echo "         Server Berjalan"
echo "================================="
echo ""
echo "Server dapat dikunjungi di localhost:9988"
echo "Atau [ALAMAT IP LAN]:9988"
echo ""
echo "Tekan Ctrl + C untuk mematikan server"
cd cbt
echo ""
pg_ctl -D ./database -l ./database.log start > /dev/null 2>&1
trap cleanup SIGINT SIGTERM EXIT
chmod +x ./main-amd64
chmod +x ./cbt/main-arm64 || true
if grep -q "main-arm64" ./cbt/.unzip.log; then
    proot -b $PREFIX/var/lib/proot-distro/installed-rootfs/alpine/usr/share:/usr/share ./main-arm64
else
    qemu-x86_64 -L $PREFIX/var/lib/proot-distro/installed-rootfs/alpine ./main-amd64
fi
