#!/data/data/com.termux/files/usr/bin/bash
echo "memulai upgrade"
rm ./cbt/up*sql
wget https://s3.ekstraordinary.com/extraordinarycbt/release-rosetta/4.6.1-linux.zip -O cbt.zip
unzip -o cbt.zip -d ./cbt
rm cbt.zip
pg_ctl -D ./cbt/database -l ./cbt/database.log start
sql=$(ls ./cbt/up*sql 2>/dev/null | head -n 1)
psql -U postgres -d exo -f "$sql"
pg_ctl -D ./cbt/database stop
clear
echo "upgrade selesai"
