#!/data/data/com.termux/files/usr/bin/bash
echo "memulai upgrade"
rm ./cbt/up*sql
wget https://s3.ekstraordinary.com/extraordinarycbt/release-rosetta/4.6.2-linux.zip -O cbt.zip
cp ./cbt/.env -f ./cbt/.env.bak
unzip -o cbt.zip -d ./cbt | tee ./cbt/.unzip.log
awk -F= '!a[$1]++' ./cbt/.env.bak ./cbt/.env > ./cbt/.env.merged
mv -f ./cbt/.env.merged ./cbt/.env
rm cbt.zip
pg_ctl -D ./cbt/database -l ./cbt/database.log start
sql=$(ls ./cbt/up*sql 2>/dev/null | head -n 1)
psql -U postgres -d exo -f "$sql"
pg_ctl -D ./cbt/database stop
chmod +x ./cbt/main-arm64 || true
clear
echo "upgrade selesai"
